### ISSUE TITLE
Doesn't compile on i386 when time_t is defined as int

### ISSUE THREAD

**Issue by lbartoletti** [sandyre/libopencad#30]
time_t is not necessary a long. On some architecture (for my case FreeBSD i386), time_t is defined as an int (and long for amd64). So, for 32 bits, libopencad doesn't compile:
 
```
lib/cadheader.h:78:5: error: constructor cannot be redeclared CADVariant( time_t val );
    ^
lib/cadheader.h:72:5: note: previous declaration is here CADVariant( int val );
```
See [types.h](https://github.com/freebsd/freebsd/blob/af3e10e5a78d3af8cef6088748978c6c612757f0/sys/x86/include/_types.h)

**Comment by drnextgis** [comment]
Any progress on this issue?

**Comment by sandyre** [comment]
Last commit fixes build?

**Comment by lbartoletti** [comment]
Yes
